### ISSUE TITLE
Deployment as a OSGi module fails on a Java EE 8 server

### ISSUE THREAD

**Issue by bjetal** [vt-middleware/ldaptive#165]
Java EE 8 (e.g. Glassfish 5) includes the Servlet 4.0 API.  Unfortunately the ldaptive jar file's OSGi configuration specifies that the servlet version must be greater than or equal to 3.1 but less than 4.  This has been confirmed for versions 1.2.1, 1.2.4 and the 2.0 pre-releases.  The exception that occurs when trying to install it as an OSGi bundle looks something like (this is on Glassfish 5):

```
  Error while starting bundle: file:/opt/glassfish/glassfish/domains/extension/autodeploy/bundles/ldaptive-1.2.1.jar: org.osgi.framework.BundleException: Unable to resolve org.ldaptive [368](R 368.0): missing requirement [org.ldaptive [368](R 368.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.servlet)(version>=3.1.0)(!(version>=4.0.0))) Unresolved requirements: [[org.ldaptive [368](R 368.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.servlet)(version>=3.1.0)(!(version>=4.0.0)))]]]

[2020-01-06T16:26:38.441-0500] [glassfish 5.1] [INFO] [] [] [tid: _ThreadID=96 _ThreadName=Thread-9] [timeMillis: 1578345998441] [levelValue: 800] [[
  org.osgi.framework.BundleException: Unable to resolve org.ldaptive [368](R 368.0): missing requirement [org.ldaptive [368](R 368.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.servlet)(version>=3.1.0)(!(version>=4.0.0))) Unresolved requirements: [[org.ldaptive [368](R 368.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.servlet)(version>=3.1.0)(!(version>=4.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
]]
```

**Comment by bjetal** [comment]
The attached is a patch we are using locally to rebuild ldaptive without this servlet version limitation.  It may be overly simplistic in that it changes the version restrictions on all libraries, not just servlet
[ldaptive-165.patch.txt](https://github.com/vt-middleware/ldaptive/files/4031940/ldaptive-165.patch.txt)

**Comment by dfish3r** [comment]
I'm inclined to bump the servlet version to v4. Any issue with that change?

**Comment by bjetal** [comment]
The problem is then it would break on older Java EE servers.

Something you might think about (not that it solves this problem) is breaking the Servlet functionality into a separate module, since it is not part of the core library functionality.

**Comment by dfish3r** [comment]
We decided to remove the servlet classes from v2. The webapp module that had dependencies on those classes had already been removed. Latest snapshot should have removed javax.servlet from the OSGi import.

**Comment by bjetal** [comment]
I was hoping for a fix in version 1, but this I understand why it make sense not to in this case.  We will work with this.
