### ISSUE TITLE
1.3.2: BlockingConnectionPool#getConnection() crashes  

### ISSUE THREAD

**Issue by rodwiddowson** [vt-middleware/ldaptive#219]
The failing line is
``` 
if (!checkOutLock.tryLock(blockWaitTime.toMillis(), TimeUnit.MILLISECONDS)) {
```

And `blockWaitTime` time is null.  Example stack
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.time.Duration.toMillis()" because "this.blockWaitTime" is null
	at org.ldaptive.pool.BlockingConnectionPool.getConnection(BlockingConnectionPool.java:131)
	at org.ldaptive.pool.PooledConnectionFactory.getConnection(PooledConnectionFactory.java:68)
	at net.shibboleth.idp.attribute.resolver.dc.ldap.impl.ConnectionFactoryValidator.validate(ConnectionFactoryValidator.java:99)
	at net.shibboleth.idp.attribute.resolver.dc.ldap.impl.LDAPDataConnector.doInitialize(LDAPDataConnector.java:152)
```

**Comment by dfish3r** [comment]
I see it. I'll cut a new release to address this.

**Comment by dfish3r** [comment]
Fixed in https://github.com/vt-middleware/ldaptive/commit/ba66587e2bf9c7ad9b5d4d67ebc811428551e950 and https://github.com/vt-middleware/ldaptive/commit/6db401d7347e5d514d5981db3a4f967e0f1c8bff
