### ISSUE TITLE
BeanGenerator

### ISSUE THREAD

**Issue by sysmat** [vt-middleware/ldaptive#35]
version: 1.1.0-SNAPSHOT

Snippets of code:
----------------------
final static String[] OBJECT_CLASSES = {"top","person","inetOrgPerson","organizationalPerson","posixAccount","shadowAccount","eduPerson","schacContactLocation","schacEmployeeInfo","schacEntryConfidentiality","schacEntryMetadata","schacLinkageIdentifiers","schacLinkageIdentifiers","schacPersonalCharacteristics","schacUserEntitlements"};
....
generator.setPackageName("morez.schema.beans");   
generator.setUseOperationalAttributes(true);
generator.setUseOptionalAttributes(true);
generator.setIncludeSuperiorClasses(true);
generator.write("target/generated-test-sources/ldaptive");

Exception:
----------------
java.lang.IllegalArgumentException: Class already exists: morez.schema.beans.SchacLinkageIdentifiers
	at org.ldaptive.beans.generate.BeanGenerator.createClass(BeanGenerator.java:544)
	at org.ldaptive.beans.generate.BeanGenerator.generate(BeanGenerator.java:369)
	at ldap.ldaptive.LdaptiveBeanGenerator.main(LdaptiveBeanGenerator.java:60)
Caused by: com.sun.codemodel.JClassAlreadyExistsException

Explanation:
------------------
But there is no folder generated-test-sources so there is no class SchacLinkageIdentifiers

Regards, Tomaz

**Comment by sysmat** [comment]
Pardon, my mistake.

Regards, Tomaz
