### ISSUE TITLE
LdapURL incurs exception if URL string ends with slash

### ISSUE THREAD

**Issue by ernieKovak** [vt-middleware/ldaptive#40]
I'm creating a DefaultConnectionFactory, using a ConnectionConfig instance to whose setLdapUrl method I pass a URL string obtained from a eureka service registry lookup. The string ends with a slash, e.g.:

ldaps://123.45.67.890:636/

This results at connection time in a NumberFormatException in the LdapURL constructor.

Caused by: java.lang.NumberFormatException: For input string: "636/"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at org.ldaptive.LdapURL.<init>(LdapURL.java:78)
at org.ldaptive.LdapURL.<init>(LdapURL.java:51)
at org.ldaptive.provider.jndi.JndiProvider.getJndiConnectionFactory(JndiProvider.java:199)
at org.ldaptive.provider.jndi.JndiProvider.getConnectionFactory(JndiProvider.java:108)
at org.ldaptive.DefaultConnectionFactory.getConnection(DefaultConnectionFactory.java:142)

**Comment by dfish3r** [comment]
I believe this was inadvertently fixed in this commit:
https://github.com/vt-middleware/ldaptive/commit/8fa13ce0336ad8d61c7ecd01d8c13b36520838af

Can you confirm that the 1.1.0-SNAPSHOT fixes this issue?

**Comment by ernieKovak** [comment]
Yep, looks like that fixes it. Any idea when 1.1 will be released?

**Comment by dfish3r** [comment]
I'm hoping the next release will be in June.
